server:
  port: 8080

spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphql

  application:
    name: portfolio

aws:
  region: us-east-1
  s3:
    bucket-name: portfolio-insights-uploads

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics